//! Phase 9 - Python / Rust numerical cross-validation.
//!
//! Differential validation of the Rust implementation against the Python
//! `sectionproperties` reference implementation. Reference data is generated by
//! `generate_cross_validation_reference.py` into
//! `tests/reference/cross_validation/`. Each case stores the exact polygon
//! coordinates used by Python, so Rust rebuilds an identical geometry rather
//! than relying on a second parameterisation of the same section.
//!
//! Every quantity is normalised by a characteristic magnitude of the same
//! physical kind (never absolute-only, never a blind `max(1.0, scale)`).
//! Status: EXACT / NUMERICAL / MESH_DIFFERENCE /
//! REFERENCE_EXECUTION_FAILURE / MISMATCH.

use section_properties::geometry::{Point, Polygon};
use section_properties::mesh::MeshControl;
use section_properties::plastic::warping_fem::compute_fem_warping_solution;
use section_properties::section::Section;
use section_properties::section_properties::SectionProperties;
use serde::Deserialize;
use std::path::{Path, PathBuf};

const REF_DIR: &str = "tests/reference/cross_validation";

#[derive(Debug, Deserialize)]
struct IndexFile {
    environment: serde_json::Value,
    cases: Vec<CaseEntry>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct CaseEntry {
    case: String,
    description: String,
    mesh_size: f64,
    #[serde(default)]
    warping_error: Option<String>,
    file: String,
}

#[derive(Debug, Deserialize)]
struct GeometryRef {
    outer: Vec<Vec<f64>>,
    #[serde(default)]
    holes: Vec<Vec<Vec<f64>>>,
}

#[derive(Debug, Deserialize)]
struct WarpingRef {
    j: f64,
    iw: f64,
    shear_centre: Vec<f64>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct PropertiesRef {
    area: f64,
    centroid: Vec<f64>,
    ixx: f64,
    iyy: f64,
    ixy: f64,
    i11: f64,
    i22: f64,
    phi: f64,
    zxx_plus: f64,
    zyy_plus: f64,
    rx: f64,
    ry: f64,
    #[serde(default)]
    warping: Option<WarpingRef>,
    #[serde(default)]
    warping_error: Option<String>,
}

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct CaseRef {
    case: String,
    description: String,
    mesh_size: f64,
    geometry: GeometryRef,
    properties: PropertiesRef,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Status {
    Exact,
    Numerical,
    MeshDifference,
    #[allow(dead_code)]
    ReferenceFailure,
    Mismatch,
}

impl Status {
    fn label(self) -> &'static str {
        match self {
            Status::Exact => "EXACT",
            Status::Numerical => "NUMERICAL",
            Status::MeshDifference => "MESH_DIFFERENCE",
            Status::ReferenceFailure => "REFERENCE_EXECUTION_FAILURE",
            Status::Mismatch => "MISMATCH",
        }
    }
}

fn compare(
    quantity: &str,
    python: f64,
    rust: f64,
    scale: f64,
    tol: f64,
) -> (String, f64, f64, Status) {
    let abs = (rust - python).abs();
    let rel = abs / scale.abs().max(f64::MIN_POSITIVE);
    let status = if abs == 0.0 {
        Status::Exact
    } else if rel <= tol {
        Status::Numerical
    } else {
        Status::Mismatch
    };
    println!(
        "    {:<16} py={:>16.8e} rust={:>16.8e} abs={:>11.3e} rel={:>11.3e} tol={:>9.1e}  {}",
        quantity,
        python,
        rust,
        abs,
        rel,
        tol,
        status.label()
    );
    (quantity.to_string(), abs, rel, status)
}

fn to_polygon(ring: &[Vec<f64>]) -> Polygon {
    Polygon::new(ring.iter().map(|p| Point::new(p[0], p[1])).collect())
}

fn build_section(g: &GeometryRef) -> Section {
    let outer = to_polygon(&g.outer);
    let holes: Vec<Polygon> = g.holes.iter().map(|h| to_polygon(h)).collect();
    Section::new(outer, holes)
}

fn ref_dir() -> PathBuf {
    let p = Path::new(REF_DIR);
    if p.join("index.json").exists() {
        return p.to_path_buf();
    }
    let up = Path::new("..").join(REF_DIR);
    if up.join("index.json").exists() {
        return up;
    }
    panic!(
        "reference data not found at {}; run generate_cross_validation_reference.py first",
        REF_DIR
    );
}

fn case_filter() -> Option<Vec<String>> {
    let raw = std::env::var("CV_CASES").ok()?;
    let list: Vec<String> = raw
        .split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
        .collect();
    if list.is_empty() { None } else { Some(list) }
}

fn include(filter: &Option<Vec<String>>, case: &str) -> bool {
    match filter {
        None => true,
        Some(list) => list.iter().any(|c| c == case),
    }
}

fn mesh_control(size: f64) -> MeshControl {
    match std::env::var("CV_MESH").as_deref() {
        Ok("coarse") => MeshControl::Coarse,
        Ok("normal") => MeshControl::Normal,
        Ok("fine") => MeshControl::Fine,
        Ok("veryfine") => MeshControl::VeryFine,
        _ => MeshControl::Custom(size),
    }
}

#[test]
fn geometric_cross_validation() {
    let dir = ref_dir();
    let index: IndexFile =
        serde_json::from_str(&std::fs::read_to_string(dir.join("index.json")).unwrap()).unwrap();
    println!("\n=== Python reference environment ===");
    println!(
        "{}",
        serde_json::to_string_pretty(&index.environment).unwrap()
    );

    let mut mismatches: Vec<String> = Vec::new();
    let mut n = 0usize;
    let filter = case_filter();

    for entry in &index.cases {
        if !include(&filter, &entry.case) {
            continue;
        }
        let case: CaseRef =
            serde_json::from_str(&std::fs::read_to_string(dir.join(&entry.file)).unwrap()).unwrap();
        println!("\n### {} - {}", case.case, case.description);

        let section = build_section(&case.geometry);
        let props = SectionProperties::from_section(&section);
        let a = case.properties.area;
        let isc = a * a; // inertia scale ~ A^2
        let imax = case.properties.ixx.abs().max(case.properties.iyy.abs());
        let t = 1e-8;

        let mut out = vec![
            compare("area", a, props.area, a, t),
            compare(
                "centroid_x",
                case.properties.centroid[0],
                props.centroid.x,
                a.sqrt(),
                t,
            ),
            compare(
                "centroid_y",
                case.properties.centroid[1],
                props.centroid.y,
                a.sqrt(),
                t,
            ),
            compare("ixx", case.properties.ixx, props.ix, isc, t),
            compare("iyy", case.properties.iyy, props.iy, isc, t),
            compare("ixy", case.properties.ixy, props.ixy, imax.max(1e-300), t),
            compare("i11", case.properties.i11, props.principal.i11, isc, t),
            compare("i22", case.properties.i22, props.principal.i22, isc, t),
            compare("rx", case.properties.rx, props.gyration.rx, a.sqrt(), t),
            compare("ry", case.properties.ry, props.gyration.ry, a.sqrt(), t),
            compare(
                "zxx_plus",
                case.properties.zxx_plus,
                props.zxx_plus,
                case.properties.zxx_plus.abs().max(isc / a.sqrt()),
                t,
            ),
            compare(
                "zyy_plus",
                case.properties.zyy_plus,
                props.zyy_plus,
                case.properties.zyy_plus.abs().max(isc / a.sqrt()),
                t,
            ),
        ];

        // phi: CONVENTION DIFFERENCE (documented, NOT a defect).
        // Rust: radians, phi = 0.5*atan2(2*Ixy, Ixx - Iyy), CCW positive.
        // Python: degrees, opposite sense, phi_py_rad = -phi_rust (mod pi).
        let phi_py = case.properties.phi.to_radians();
        let degenerate = (case.properties.i11 - case.properties.i22).abs()
            <= 1e-9 * case.properties.i11.abs().max(case.properties.i22.abs());
        if degenerate {
            println!("    phi              (undefined: i11 == i22; skipped)");
        } else {
            let mut d = (phi_py + props.principal.phi).rem_euclid(std::f64::consts::PI);
            if d > std::f64::consts::PI / 2.0 {
                d -= std::f64::consts::PI;
            }
            let st = if d.abs() <= 1e-8 {
                Status::Numerical
            } else {
                Status::Mismatch
            };
            println!(
                "    {:<16} py={:>16.8e} rust={:>16.8e} abs={:>11.3e} rel={:>11.3e} tol={:>9.1e}  {}",
                "phi(mapped)",
                phi_py,
                props.principal.phi,
                d.abs(),
                d.abs() / std::f64::consts::PI,
                1e-8,
                st.label()
            );
            out.push((
                "phi(mapped)".to_string(),
                d.abs(),
                d.abs() / std::f64::consts::PI,
                st,
            ));
        }

        n += out.len();
        for (name, _, rel, st) in &out {
            if *st == Status::Mismatch {
                mismatches.push(format!("{}: {} rel={:.3e}", case.case, name, rel));
            }
        }
    }

    println!(
        "\n=== geometric summary: {} comparisons, {} mismatches ===",
        n,
        mismatches.len()
    );
    for m in &mismatches {
        println!("  MISMATCH {}", m);
    }
    assert!(mismatches.is_empty(), "{} mismatches", mismatches.len());
}

/// Warping differential comparison; ~200 s per case, so run with `--ignored`.
#[test]
#[ignore = "warping FEM comparison is slow (~200 s per case); run explicitly with --ignored"]
fn warping_cross_validation() {
    let dir = ref_dir();
    let index: IndexFile =
        serde_json::from_str(&std::fs::read_to_string(dir.join("index.json")).unwrap()).unwrap();
    let nu = 0.3;
    let (jt, iwt, sct) = (5e-2, 1e-1, 5e-2);
    let (mut md, mut fail, mut ok) = (0usize, 0usize, 0usize);
    let filter = case_filter();

    for entry in &index.cases {
        if !include(&filter, &entry.case) {
            continue;
        }
        let case: CaseRef =
            serde_json::from_str(&std::fs::read_to_string(dir.join(&entry.file)).unwrap()).unwrap();
        let Some(w) = case.properties.warping.as_ref() else {
            println!(
                "\n### {} - no Python warping reference ({}) -> REFERENCE_EXECUTION_FAILURE",
                case.case,
                case.properties
                    .warping_error
                    .clone()
                    .or(entry.warping_error.clone())
                    .unwrap_or_else(|| "not computed".to_string())
            );
            fail += 1;
            continue;
        };

        let section = build_section(&case.geometry);
        let props = SectionProperties::from_section(&section);
        let fem = match compute_fem_warping_solution(
            &section,
            &props,
            nu,
            mesh_control(case.mesh_size),
        ) {
            Ok(f) => f,
            Err(e) => {
                println!("\n### {} - Rust FEM failed: {:?}", case.case, e);
                fail += 1;
                continue;
            }
        };

        let l = case.properties.area.sqrt();
        // CONVENTION DIFFERENCE: Rust's shear centre is an offset from the
        // centroid; Python's is absolute.
        let sx = props.centroid.x + fem.shear_center.x;
        let sy = props.centroid.y + fem.shear_center.y;
        println!(
            "\n### {} - warping (n_dof={} n_elem={} J_raw={:.6e} J_fem={:.6e} fallback={})",
            case.case,
            fem.omega.len(),
            fem.elements.len(),
            fem.j_raw,
            fem.j_fem,
            fem.used_analytical_fallback
        );
        let mut out = vec![
            compare("J", w.j, fem.j, w.j.abs(), jt),
            compare("Iw", w.iw, fem.iw, w.iw.abs(), iwt),
            compare("shear_centre_x", w.shear_centre[0], sx, l, sct),
            compare("shear_centre_y", w.shear_centre[1], sy, l, sct),
        ];
        for (_, _, _, st) in out.iter_mut() {
            if *st == Status::Mismatch {
                *st = Status::MeshDifference;
            }
        }
        for (_, _, _, st) in &out {
            match *st {
                Status::MeshDifference => md += 1,
                Status::Exact | Status::Numerical => ok += 1,
                _ => fail += 1,
            }
        }
    }

    println!(
        "\n=== warping summary: ok={} mesh_difference={} failures={} ===",
        ok, md, fail
    );
    assert_eq!(fail, 0, "warping reference/solver failures must be zero");
}
